In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
from rflearn.env import GridWorld
from copy import deepcopy

In [2]:
from rflearn.policy import PolicyIteration, ValueIteration

_grid = [
    [0, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 0],
]
# grid = GridWorld(grid=_grid, terminals=[0])
grid = GridWorld(4, 4)
value = np.zeros(shape=len(grid.S))
policy = np.ones(shape=(len(grid.S), len(grid.A))) / len(grid.A)

In [3]:
pi_model = PolicyIteration(theta=0.001)
pi_model.fit(grid, value, policy, gamma=1)
pi_model.transform()

print(pi_model.value.reshape(grid.shape))

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


In [4]:
pi_model.policy

array([[0.25, 0.25, 0.25, 0.25],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.5 , 0.5 , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.5 , 0.  , 0.5 , 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.  , 0.5 , 0.  , 0.5 ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.5 , 0.  , 0.  , 0.5 ],
       [0.  , 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.  , 1.  ],
       [0.25, 0.25, 0.25, 0.25]])

In [5]:
vi_model = ValueIteration(theta=0.00001)
vi_model.fit(grid, value, policy, gamma=1)
vi_model.transform()

print(vi_model.value.reshape(grid.shape))

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


In [9]:
vi_model.policy

array([[0.25, 0.25, 0.25, 0.25],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.5 , 0.5 , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.5 , 0.  , 0.5 , 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.  , 1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.  , 0.5 , 0.  , 0.5 ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.5 , 0.  , 0.  , 0.5 ],
       [0.  , 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.  , 1.  ],
       [0.25, 0.25, 0.25, 0.25]])