In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
from rflearn.env import GridWorld
from rflearn.algo import PolicyIteration, ValueIteration

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
# _grid = [
#     [0, 1, 1, 1, 1, 1, 1],
#     [0, 0, 0, 0, 0, 0, 0],
#     [1, 1, 1, 1, 1, 1, 0],
#     [0, 0, 0, 0, 0, 0, 0],
# ]
# grid = GridWorld(grid=_grid, terminals=[0])
grid = GridWorld(4, 4)
value = np.zeros(shape=len(grid.S))
policy = np.ones(shape=(len(grid.S), len(grid.A))) / len(grid.A)

pi_model = PolicyIteration(env=grid, value=value, policy=policy)
vi_model = ValueIteration(env=grid, value=value, policy=policy)

In [16]:
pi_model.fit(gamma=1, theta=0.001)
pi_model.transform()

print('Value Function\n', pi_model.value.reshape(grid.shape))
print('\nPolicy \n', pi_model.policy)

Value Function
 [[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]

Policy 
 [[0.25 0.25 0.25 0.25]
 [0.   0.   1.   0.  ]
 [0.   0.   1.   0.  ]
 [0.   0.5  0.5  0.  ]
 [1.   0.   0.   0.  ]
 [0.5  0.   0.5  0.  ]
 [0.25 0.25 0.25 0.25]
 [0.   1.   0.   0.  ]
 [1.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.   0.5  0.   0.5 ]
 [0.   1.   0.   0.  ]
 [0.5  0.   0.   0.5 ]
 [0.   0.   0.   1.  ]
 [0.   0.   0.   1.  ]
 [0.25 0.25 0.25 0.25]]


In [17]:
vi_model.fit(gamma=1, theta=0.001)
vi_model.transform()

print('Value Function\n', vi_model.value.reshape(grid.shape))
print('\nPolicy \n', vi_model.policy)

Value Function
 [[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]

Policy 
 [[0.25 0.25 0.25 0.25]
 [0.   0.   1.   0.  ]
 [0.   0.   1.   0.  ]
 [0.   0.5  0.5  0.  ]
 [1.   0.   0.   0.  ]
 [0.5  0.   0.5  0.  ]
 [0.25 0.25 0.25 0.25]
 [0.   1.   0.   0.  ]
 [1.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.   0.5  0.   0.5 ]
 [0.   1.   0.   0.  ]
 [0.5  0.   0.   0.5 ]
 [0.   0.   0.   1.  ]
 [0.   0.   0.   1.  ]
 [0.25 0.25 0.25 0.25]]
