In [10]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
from rflearn.env import GridWorld
from rflearn.algo import PolicyIteration, ValueIteration
from rflearn.algo import TabularPolicy, TabularQValue

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
# _grid = [
#     [0, 1, 1, 1, 1, 1, 1],
#     [0, 0, 0, 0, 0, 0, 0],
#     [1, 1, 1, 1, 1, 1, 0],
#     [0, 0, 0, 0, 0, 0, 0],
# ]
# grid = GridWorld(grid=_grid, terminals=[0])
grid = GridWorld(4, 4)
qvalue = TabularQValue(grid.S, grid.A)
policy = TabularPolicy(grid.S, grid.A)

pi_model = PolicyIteration(env=grid, qvalue=qvalue, policy=policy)
vi_model = ValueIteration(env=grid, qvalue=qvalue, policy=policy)

In [12]:
pi_model.fit(gamma=1, theta=0.001)
pi_model.transform()

print('Value Function\n', pi_model.get_all_values().reshape(grid.shape))
print('\nPolicy \n', pi_model.policy.to_numpy())

Value Function
 [[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]

Policy 
 [[0.25 0.25 0.25 0.25]
 [0.   0.   1.   0.  ]
 [0.   0.   1.   0.  ]
 [0.   0.5  0.5  0.  ]
 [1.   0.   0.   0.  ]
 [0.5  0.   0.5  0.  ]
 [0.25 0.25 0.25 0.25]
 [0.   1.   0.   0.  ]
 [1.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.   0.5  0.   0.5 ]
 [0.   1.   0.   0.  ]
 [0.5  0.   0.   0.5 ]
 [0.   0.   0.   1.  ]
 [0.   0.   0.   1.  ]
 [0.25 0.25 0.25 0.25]]


In [13]:
vi_model.fit(gamma=1, theta=0.001)
vi_model.transform()

print('Value Function\n', vi_model.get_all_values().reshape(grid.shape))
print('\nPolicy \n', vi_model.policy.to_numpy())

Value Function
 [[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]

Policy 
 [[0.25 0.25 0.25 0.25]
 [0.   0.   1.   0.  ]
 [0.   0.   1.   0.  ]
 [0.   0.5  0.5  0.  ]
 [1.   0.   0.   0.  ]
 [0.5  0.   0.5  0.  ]
 [0.25 0.25 0.25 0.25]
 [0.   1.   0.   0.  ]
 [1.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.   0.5  0.   0.5 ]
 [0.   1.   0.   0.  ]
 [0.5  0.   0.   0.5 ]
 [0.   0.   0.   1.  ]
 [0.   0.   0.   1.  ]
 [0.25 0.25 0.25 0.25]]
